#ifndef ACTION_ENUM_H
#define ACTION_ENUM_H

enum ActionEnum {
	MOVE_CAMERA_LEFT,
	MOVE_CAMERA_RIGHT,
	MOVE_CAMERA_FORWARD,
	MOVE_CAMERA_BACKWARD,
	MOVE_CAMERA_UP,
	MOVE_CAMERA_DOWN,

	STOP_CAMERA_LEFT,
	STOP_CAMERA_RIGHT,
	STOP_CAMERA_FORWARD,
	STOP_CAMERA_BACKWARD,
	STOP_CAMERA_UP,
	STOP_CAMERA_DOWN,

	ROTATE_DEBUG_CAMERA
};

#endif 